modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"

[[mods]]
modId="sneakfall"
version="${version}"
displayName="轻功"
description="坠落时按住潜行减免摔落伤害（可配置阶段/判定模式/减免量）"
authors="shinano"

[[dependencies.sneakfall]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"

[[dependencies.sneakfall]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
